<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-IIMQB4J" failures="1" tests="1" name="TestFour" time="13.734" errors="0" timestamp="18 Mar 2022 13:48:32 GMT">
  <testcase classname="testcases.FourTest" name="fourTest" time="13.126">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testcases.FourTest.fourTest(FourTest.java:24)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- fourTest -->
</testsuite> <!-- TestFour -->
